[tool.poetry]
name = "mosek-license-server"
version = "0.0.0"
description = "Expose a mosek license via a nginx server"
authors = ["Thomas Schmelzer <thomas.schmelzer@gmail.com>"]
license = "Apache 2.0"
readme = "readme.md"
repository = "https://github.com/tschm/mosek-license-server"
packages = [{include = "mosek_license"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.14"

[tool.poetry.group.test.dependencies]
numpy = ">=2.0"
mosek = ">=10.2.0"
pytest = "8.3.3"
pytest-cov = "6.0.0"
pre-commit = "4.0.1"

[build-system]
requires = ["poetry>=1.6.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
demo = "demo.demo:main"

[tool.ruff]
select = ["E", "F", "I"]
line-length = 100
target-version = "py310"
exclude = [
    "*__init__.py"
]
ignore = ["E402"]
