name: Analyse with deptry

on:
  [push]

jobs:
  run-deptry:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/deptry
        with:
          source-folder: "mosek_license"
