name: Linting

on:
  push

jobs:
  release:
    runs-on: ubuntu-latest

    # Steps represent matrix sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: readme.md


      - name: Run black on mosek_license folder
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./mosek_license"


      - name: Run black on tests folder
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./tests"
