name: Upload Python Package

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: none
      contents: write   # needed to upload into dist branch
    steps:
      - uses: cvxgrp/.github/actions/uv/build@main

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: release

    permissions:
      # This permission is required for trusted publishing.
      id-token: write
      contents: read
    steps:
      - uses: cvxgrp/.github/actions/publish@main
