name: Upload Python Package

permissions:
  contents: read
  pull-requests: write  # Needed for Dependabot to create PRs
  issues: write         # Needed for creating issues
  checks: write         # Needed for posting test results

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/build@main

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: release

    permissions:
      # This permission is required for trusted publishing.
      id-token: write

    steps:
      - uses: cvxgrp/.github/actions/publish@main
